# Site settings
title: Análise de Dados 1
email: daniyel.rocha@ccc.ufcg.edu.br
description: > # this means to ignore newlines until "baseurl:"
  Conteúdo das atividades da disciplina de Análise de Dados 1, Universidade Federal de Campina Grande (UFCG)
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: dnrocha
github_username:  dnrocha1
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown